### ISSUE TITLE
Gala crashes after monitor is turned off

### ISSUE THREAD

**Issue by sryze** [elementary/gala#1426]
### What Happened?

I left my computer idle for some time and when I got back and logged in again, all programs were closed, as if I rebooted the system. After inspecting the logs, I found that `gala` crashed after ~20 minutes of being idle.

### Steps to Reproduce

1. Do some important work
2. Leave the computer untouched for a few minutes
3. Wait for the screen lock
4. Wait some more
5. Log back in

### Expected Behavior

Expected to see everything the same as I left it.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

Last log record prior to these events below was at 13:08. Unfortunately, I can't attach it as it contains some private information. I think this is roughly when I left the PC alone.

```shell
May 21 13:30:25 base gala[2184]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
May 21 13:30:25 base gala[2184]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: value "-30" of type 'gint' is invalid or out of range for property 'y2' of type 'gint'
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
May 21 13:30:25 base gala[2184]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
May 21 13:30:25 base gala[2184]: ../../../gobject/gsignal.c:2736: instance '0x7f9b28008e60' has no handler with id '22909'
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: value "-30" of type 'gint' is invalid or out of range for property 'y2' of type 'gint'
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
May 21 13:30:25 base gala[2184]: The program 'gala' received an X Window System error.
                                 This probably reflects a bug in the program.
                                 The error was 'BadValue (integer parameter out of range for operation)'.
                                   (Details: serial 3288691 error_code 2 request_code 138 (XFIXES) minor_code 31)
                                   (Note to programmers: normally, X errors are reported asynchronously;
                                    that is, you will receive the error a while after causing it.
                                    To debug your program, run it with the GDK_SYNCHRONIZE environment
                                    variable to change this behavior. You can then get a meaningful
                                    backtrace from your debugger if you break on the gdk_x_error() function.)
```

[journal.txt](https://github.com/elementary/gala/files/8747260/journal.txt)

### Hardware Info

GPU: Radeon RX 580
Single-monitor setup, 1920x1080, no scaling, connected via HDMI port

Power settings:
* Turn off display after inactive for: 15 minutes
* Suspend after inactive for: 1 hour

```
$ lspci -nnk | egrep -i --color 'vga|3d|2d' -A3 | grep 'in use'
	Kernel driver in use: amdgpu

$ lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:128 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:f7e00000-f7e3ffff memory:c0000-dffff

```

Details of installed amdgpu packages:

```
libdrm-amdgpu1/focal-updates,now 2.4.107-8ubuntu1~20.04.2 amd64 [installed,automatic]
libdrm-amdgpu1/focal-updates,now 2.4.107-8ubuntu1~20.04.2 i386 [installed,automatic]
xserver-xorg-video-amdgpu/focal,now 19.1.0-1 amd64 [installed,automatic]
```

**Comment by sryze** [comment]
Actually, I was able to reproduce it again by just click on the Lock button and waiting a little bit (under 30 seconds) while the login screen appears again.

[journal3.txt](https://github.com/elementary/gala/files/8747295/journal3.txt)

**Comment by sryze** [comment]
I have now re-installed elementaryOS 6.1 but the crash still happens. It also happens when I simply disconnect the HDMI cable, so not really related to screen lock it seems.

```
Oct 19 11:00:13 base gala[2055]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
Oct 19 11:00:13 base gala[2055]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: value "-30" of type 'gint' is invalid or out of range for property 'y2' of type 'gint'
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
Oct 19 11:00:13 base gala[2055]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
Oct 19 11:00:13 base gala[2055]: ../../../gobject/gsignal.c:2736: instance '0x7f0f08007c60' has no handler with id '315'
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: value "-30" of type 'gint' is invalid or out of range for property 'y2' of type 'gint'
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[2055]: The program 'gala' received an X Window System error.
                                 This probably reflects a bug in the program.
                                 The error was 'BadValue (integer parameter out of range for operation)'.
                                   (Details: serial 439936 error_code 2 request_code 138 (XFIXES) minor_code 31)
                                   (Note to programmers: normally, X errors are reported asynchronously;
                                    that is, you will receive the error a while after causing it.
                                    To debug your program, run it with the GDK_SYNCHRONIZE environment
                                    variable to change this behavior. You can then get a meaningful
                                    backtrace from your debugger if you break on the gdk_x_error() function.)
Oct 19 11:00:13 base gsd-xsettings[1927]: Failed to get current display configuration state: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Oct 19 11:00:13 base gnome-session[1776]: gnome-session-binary[1776]: WARNING: Application 'gala.desktop' killed by signal 5
Oct 19 11:00:13 base gnome-session-binary[1776]: WARNING: Application 'gala.desktop' killed by signal 5
Oct 19 11:00:13 base gsd-xsettings[1927]: Failed to get current display configuration state: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Mutter.DisplayConfig" does not exist
Oct 19 11:00:13 base plank.desktop[4318]: ATTENTION: default value of option mesa_glthread overridden by environment.
Oct 19 11:00:13 base gala[53436]: meta_monitor_manager_get_logical_monitor_from_number: assertion '(unsigned int) number < g_list_length (manager->logical_monitors)' failed
Oct 19 11:00:13 base gala[53436]: meta_workspace_get_work_area_for_monitor: assertion 'logical_monitor != NULL' failed
Oct 19 11:00:13 base gala.desktop[53436]: Window manager warning: Trying to re-add keybinding "switch-to-workspace-last".
Oct 19 11:00:13 base gala.desktop[53436]: Window manager warning: Trying to re-add keybinding "move-to-workspace-last".
Oct 19 11:00:13 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:13 base gala[53436]: value "-30" of type 'gint' is invalid or out of range for property 'y2' of type 'gint'
Oct 19 11:00:13 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base plank.desktop[4318]: ATTENTION: default value of option mesa_glthread overridden by environment.
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: meta_display_get_monitor_geometry: assertion 'monitor >= 0 && monitor < n_logical_monitors' failed
Oct 19 11:00:14 base gala[53436]: The program 'gala' received an X Window System error.
                                  This probably reflects a bug in the program.
                                  The error was 'BadValue (integer parameter out of range for operation)'.
                                    (Details: serial 395 error_code 2 request_code 138 (XFIXES) minor_code 31)
                                    (Note to programmers: normally, X errors are reported asynchronously;
                                     that is, you will receive the error a while after causing it.
                                     To debug your program, run it with the GDK_SYNCHRONIZE environment
                                     variable to change this behavior. You can then get a meaningful
                                     backtrace from your debugger if you break on the gdk_x_error() function.)
Oct 19 11:00:14 base gnome-session[1776]: gnome-session-binary[1776]: WARNING: Application 'gala.desktop' killed by signal 5
Oct 19 11:00:14 base gnome-session[1776]: gnome-session-binary[1776]: WARNING: App 'gala.desktop' respawning too quickly
Oct 19 11:00:14 base gnome-session-binary[1776]: WARNING: Application 'gala.desktop' killed by signal 5
Oct 19 11:00:14 base gnome-session-binary[1776]: Unrecoverable failure in required component gala.desktop
Oct 19 11:00:14 base gnome-session[1776]: gnome-session-binary[1776]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Oct 19 11:00:14 base gnome-session-binary[1776]: WARNING: App 'gala.desktop' respawning too quickly
Oct 19 11:00:14 base gnome-session-binary[1776]: CRITICAL: We failed, but the fail whale is dead. Sorry....
```

[gala-crash-journalctl.txt](https://github.com/elementary/gala/files/9819848/gala-crash-journalctl.txt)

**Comment by sryze** [comment]
Stack trace:

```
Thread 1 (Thread 0x7ffff4cd45c0 (LWP 28924)):
#0  0x00007ffff7e8c295 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7e8ec7c in g_log_writer_default () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7e8ced7 in g_log_structured_array () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7e8d904 in g_log_structured_standard () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff72cccda in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff72d9d03 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007ffff65a628b in _XError () at /lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007ffff65a2ff7 in  () at /lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007ffff65a3095 in  () at /lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007ffff65a401d in _XReply () at /lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007ffff659f7f1 in XSync () at /lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007ffff659f88f in  () at /lib/x86_64-linux-gnu/libX11.so.6
#12 0x00007ffff6f51de7 in XFixesCreatePointerBarrier () at /lib/x86_64-linux-gnu/libXfixes.so.3
#13 0x00007ffff6fd5aea in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#14 0x00007ffff6fb692d in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#15 0x00007ffff7dee526 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff7df0378 in g_object_new_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7df06cd in g_object_new () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00005555555dfa2c in gala_barrier_construct (object_type=Python Exception <class 'gdb.error'> No type named TypeNode.: 
, display=0x55555599e000, x1=0, y1=0, x2=0, y2=-30, directions=META_BARRIER_DIRECTION_POSITIVE_X) at ../src/HotCorners/HotCorner.vala:27
#19 0x00005555555dfa85 in gala_barrier_new (display=0x55555599e000, x1=0, y1=0, x2=0, y2=-30, directions=META_BARRIER_DIRECTION_POSITIVE_X) at ../src/HotCorners/HotCorner.vala:26
#20 0x00005555555e095c in gala_hot_corner_add_barriers (self=0x555555aaac20, display=0x55555599e000, x=0, y=0, hot_corner_position=0x555555a4ddc0 "hotcorner-bottomleft") at ../src/HotCorners/HotCorner.vala:85
#21 0x00005555555e0378 in gala_hot_corner_construct (object_type=Python Exception <class 'gdb.error'> No type named TypeNode.: 
, display=0x55555599e000, x=0, y=0, hot_corner_position=0x555555a4ddc0 "hotcorner-bottomleft") at ../src/HotCorners/HotCorner.vala:66
#22 0x00005555555e03c3 in gala_hot_corner_new (display=0x55555599e000, x=0, y=0, hot_corner_position=0x555555a4ddc0 "hotcorner-bottomleft") at ../src/HotCorners/HotCorner.vala:65
#23 0x00005555555e2288 in gala_hot_corner_manager_add_hotcorner (self=0x555555a989a0, x=0, y=0, hot_corner_position=0x55555562a125 "hotcorner-bottomleft") at ../src/HotCorners/HotCornerManager.vala:63
#24 0x00005555555e1d80 in gala_hot_corner_manager_configure (self=0x555555a989a0) at ../src/HotCorners/HotCornerManager.vala:42
#25 0x00005555555e198c in _gala_hot_corner_manager_configure_meta_monitor_manager_monitors_changed (_sender=0x5555556ebb40, self=0x555555a989a0) at ../src/HotCorners/HotCornerManager.vala:32
#26 0x00007ffff7de8802 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff7dfc814 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff7e07bbe in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff7e080f3 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff6fca9a1 in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#31 0x00007ffff6fcdfd7 in meta_monitor_manager_rebuild_derived () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#32 0x00007ffff6fe0b7d in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#33 0x00007ffff6fcaa5c in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#34 0x00007ffff6fcc77a in meta_monitor_manager_ensure_configured () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#35 0x00007ffff6fe11e8 in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#36 0x00007ffff6fd3851 in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#37 0x00007ffff6fd5406 in  () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#38 0x00007ffff7e8617d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff7e86400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff7e866f3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff70103d0 in meta_run () at /lib/x86_64-linux-gnu/libmutter-6.so.0
#42 0x00005555555906ab in gala_main (args=0x7fffffffe438, args_length1=1) at ../src/Main.vala:121
#43 0x00005555555906ef in main (argc=2, argv=0x7fffffffe438) at ../src/Main.vala:29
```
