### ISSUE TITLE
Program crashing let desktop session collapse

### ISSUE THREAD

**Issue by davidak** [elementary/gala#1453]
### What Happened?

I opened a new browser window (STRG + N), Chrome crashed (7 times in 5 minutes) and the desktop session collapsed.

I see the "Something has gone wrong." screen and can login again, but my work is lost.

Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1356392

### Steps to Reproduce

0. have 780 browser tabs open
1. create another tab/window
2. browser crash
3. desktop crash

### Expected Behavior

stable system, no crash

at least fail in a user-friendly way

### OS Version

Other Linux

NixOS 22.05.2397.5c211b47aea

### Software Version

Latest release (I have run all updates)

touchegg-2.0.14

### Log Output

system journal: https://gist.github.com/davidak/b9a933296cda40b97ddb80df5f0cd204

in addition to chrome, also signal-desktop and touchegg crashed

```
[root@gaming:~]# coredumpctl debug 50428
           PID: 50428 (touchegg)
           UID: 1000 (davidak)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: Thu 2022-08-25 02:02:10 CEST (45min ago)
  Command Line: touchegg
    Executable: /nix/store/xk2bwmladkpcj29z85jfnyzca092f1c5-touchegg-2.0.14/bin/touchegg
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (davidak)
       Boot ID: 4e14dfe61cc145a8939d7c6fc0b368b6
    Machine ID: 7adea793c51646eb9781f0a4f62322d6
      Hostname: gaming
       Storage: /var/lib/systemd/coredump/core.touchegg.1000.4e14dfe61cc145a8939d7c6fc0b368b6.50428.1661385730000000.zst (present)
     Disk Size: 535.1K
       Message: Process 50428 (touchegg) of user 1000 dumped core.
...
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fe00e1f6c7f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fe00e1ac042 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fe00e19749c in __GI_abort () at abort.c:79
#4  0x00007fe00e50587a in ?? () from /nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib/lib/libstdc++.so.6
#5  0x00007fe00e510eaa in ?? () from /nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib/lib/libstdc++.so.6
#6  0x00007fe00e510f15 in std::terminate() () from /nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib/lib/libstdc++.so.6
#7  0x00007fe00e511168 in __cxa_throw () from /nix/store/j132k1ncfn6gjfd2f5s1gz37170rch4h-gcc-11.3.0-lib/lib/libstdc++.so.6
#8  0x0000000000423bd8 in ClientLock::ClientLock(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold] ()
#9  0x00000000004263cc in main ()
```

### Hardware Info

- Intel i9-9900K processor with 3.6GHz
- G.Skill Ripjaws 32 GB DDR4 RAM (3200 MHz)
- Samsung 970 EVO Plus 1TB NVMe M.2 SSD
- AMD Radeon RX 6600 XT graphics card with 8 GB VRAM
- Gigabyte Z390 UD motherboard
- Noctua NH-D15 cooler
- be quiet! Straight Power 11 650 Watt power supply unit
- Antec One Midi Tower case

**Comment by lenemter** [comment]
Closing as stale. If you still encounter the issue please reply here and I'll reopen it
