### ISSUE TITLE
Hang when changing wallpaper and dragging a window [$40]

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#221]
If I change a wallpaper in Juno and start to move a window while the animation is still happening, I can get Gala to hang almost every time.

---
There is a bounty on this issue in [Bountysource](https://www.bountysource.com/issues/56840934-hang-when-changing-wallpaper-and-dragging-a-window)

**Comment by donadigo** [comment]
Here's a stacktrace I was able to get from this hang:
```
Thread 1 "gala" received signal SIGINT, Interrupt.
syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38	../sysdeps/unix/sysv/linux/x86_64/syscall.S: No such file or directory.
#0  0x00007ffff3d6ca49 in syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff734ed7c in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5373d40 in clutter_x11_handle_event () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#3  0x00007ffff56fc2c3 in  () at /usr/lib/x86_64-linux-gnu/libmutter-1.so.0
#4  0x00007ffff7309fb7 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff730a1f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff730a27c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fffc45fe706 in  () at /usr/lib/x86_64-linux-gnu/gala/plugins/libwingpanel-interface.so
#8  0x00007fffc45ff0ea in  () at /usr/lib/x86_64-linux-gnu/gala/plugins/libwingpanel-interface.so
#9  0x00007ffff75e2f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff75f5cde in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff75fe4b5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff75feecf in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff53d112f in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#14 0x00007ffff538a79a in clutter_actor_continue_paint () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#15 0x00007ffff5390c15 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#16 0x00007ffff5390f70 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#17 0x00007ffff538a93c in clutter_actor_continue_paint () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#18 0x00007ffff5390ce4 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#19 0x00007ffff5390f70 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#20 0x00007ffff5717cf7 in  () at /usr/lib/x86_64-linux-gnu/libmutter-1.so.0
#21 0x00007ffff538a93c in clutter_actor_continue_paint () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#22 0x00007ffff5390ce4 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#23 0x00007ffff5390f70 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#24 0x00007ffff538a93c in clutter_actor_continue_paint () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#25 0x00007ffff5390ce4 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#26 0x00007ffff53e3c7a in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#27 0x00007ffff56fa172 in  () at /usr/lib/x86_64-linux-gnu/libmutter-1.so.0
#28 0x00007ffff538a93c in clutter_actor_continue_paint () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#29 0x00007ffff5390ce4 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#30 0x00007ffff53e7dcf in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#31 0x00007ffff53e80c3 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#32 0x00007ffff537ae74 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#33 0x00007ffff537b013 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#34 0x00007ffff537c1fb in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#35 0x00007ffff53e4c37 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#36 0x00007ffff53d07b9 in  () at /usr/lib/x86_64-linux-gnu/mutter/libmutter-clutter-1.so
#37 0x00007ffff7309fb7 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff730a1f0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff730a502 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

(Looks like something's going on with the wingpanel interface?)

**Comment by donadigo** [comment]
Confirming that this is the fault of the wingpanel interface plugin. Removing it from the plugins folder and restarting gala fixes the issue.
